$(function(){
	$("#yzmi").click(function(){
		$("#yzmi").attr("src","yzm.jsp?a="+Math.random());
	});
	$("#login").click(function(){
		if($("#username").val()==""){
			$(".modal1").modal("show");
			$("#message").text("用户名不能为空！")
			return;
		}
		 if($("#password").val()==""){
			$(".modal1").modal("show");
			$("#message").text("密码不能为空！")
			return;
		}
		 if($("#password2").val()==""){
				$(".modal1").modal("show");
				$("#message").text("确认密码不能为空！")
				return;
			}
		 if($("#yzm").val()==""){
			$(".modal1").modal("show");
			$("#message").text("请输入验证码！")
			return;
		}
		if($("#password").val()!=$("#password2").val()){
			$(".modal1").modal("show");
			$("#message").text("两次密码不一致！")
			return;
		}
		$.post("/user/register",{
			type:$("#type").val(),
			account:$("#username").val(),
			password:$("#password").val(),
			yzm:$("#yzm").val()
		},function(data){
			$(".modal1").modal("show");
			$("#message").text(data.message);
		},'json');
	});
	$("#d1").click(function(){
		$("#username").val("");
	});
	$("#d2").click(function(){
		$("#password").val("");
	});
	$("#d3").click(function(){
		$("#password2").val("");
	});
	$("#button").click(function(){
		$(".modal1").modal("hide");
	});
});
